### ISSUE TITLE
是否可以在这个的基础上加上开奖信息？

### ISSUE THREAD

**Issue by ZhikangNiu** [CS-BAOYAN/cs-baoyan-ddl#3]

**Comment by Axi404** [comment]
网页的复选框中包括：

- ”已开营“：公布了开营信息，即入营名单；私发了入营邮件
- ”已结营“：夏令营已经结束，并且已经通过途径公布优营与wl名单

**Comment by ZhikangNiu** [comment]
great

在 2024-06-28 17:38:10，Axi404 ***@***.***> 写道：


网页的复选框中包括：

”已开营“：公布了开营信息，即入营名单；私发了入营邮件
”已结营“：夏令营已经结束，并且已经通过途径公布优营与wl名单
